[package]
name = "pacman_bindings"
version = "0.1.0"
edition = "2024"
authors = ["Esteban Forero estebanmff@outlook.com"]
description = "Bindings to interact with pacman"
license = "MIT"

[dependencies]
pazckager_core = { path = "../pazckager_core" }
