[package]
name = "pazckager_core"
version = "0.1.1"
edition = "2024"
authors = ["Esteban Forero estebanmff@outlook.com"]
description = "pazckager core crate"
license = "MIT"

[dependencies]
partial_struct = "0.4.3"
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "2.0.11"
